services:
  api:
    build:
      context: .
    ports:
      - "8000:8000"
    command: poetry run uvicorn src.api.main:app --host 0.0.0.0 --port 8000

  streamlit:
    build:
      context: .
    ports:
      - "8501:8501"
    command: sh -c 'poetry run streamlit run src/app/main.py --server.port ${PORT:-8501} --server.address 0.0.0.0'
    depends_on:
      - api
