[project]
name = "churn-ticket"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "altair>=5.5.0",
    "catboost>=1.2.7",
    "duckdb>=1.2.1",
    "fastapi>=0.115.11",
    "gunicorn>=23.0.0",
    "httpx>=0.28.1",
    "pandas>=2.2.3",
    "plotly>=6.0.0",
    "polars>=1.24.0",
    "psycopg2-binary>=2.9.10",
    "pyarrow>=19.0.1",
    "pydantic>=2.10.6",
    "pytest>=8.3.5",
    "pytest-asyncio>=0.25.3",
    "python-dotenv>=1.0.1",
    "requests>=2.32.3",
    "scikit-learn>=1.6.1",
    "seaborn>=0.13.2",
    "sqlalchemy>=2.0.39",
    "streamlit>=1.43.2",
    "streamlit-extras>=0.6.0",
    "uvicorn>=0.34.0",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "jupyter>=1.1.1",
    "lightgbm>=4.6.0",
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.6.8",
    "mkdocs-mermaid2-plugin>=1.2.1",
    "mkdocstrings>=0.29.0",
    "mkdocstrings-python>=1.16.5",
    "mypy>=1.15.0",
    "notebook>=7.3.3",
    "optuna>=4.2.1",
    "pytest-cov>=6.0.0",
    "ruff>=0.11.0",
    "taskipy>=1.14.1",
    "xgboost>=2.1.4",
    "ydata-profiling>=4.14.0",
]
