apiVersion: apps/v1
kind: Deployment
metadata:
  name: churn-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: churn-app
  template:
    metadata:
      labels:
        app: churn-app
    spec:
      containers:
      - name: churn-app
        image: guttofranca/churn-ticket-app:latest
        ports:
        - containerPort: 8501
        env:
        - name: API_URL
          value: "http://churn-api-service:8000/predict"
        resources:
          requests:
            cpu: "200m"
            memory: "512Mi"
          limits:
            cpu: "800m"
            memory: "1024Mi"